
* [2015-11-05 Thu]

** Copied libpq to otb_install_dir/lib so that it is in the LD_LIBRARY_PATH when submitting jobs

#+BEGIN_QUOTE
Bonjour,

Je rencontre un problème avec la bibliothèque libpb qui est appelée par gdal via les bindings python (module gdal 1.11.0-py2.7). Ce problème n'apparaît que quand je soumets un job avec qsub (que ce soit en interactif ou sur une queue). En effet, si je lance mon script pbs comme un script bash en ligne de commande ça fonctionne :

. ./minimal.pbs

en revanche, si je fais :

qsub minimal.pbs

j'obtiens l'erreur suivante :


------------------------------------
Traceback (most recent call last):
  File "/home/user5/qtis/inglada/importgdal.py", line 1, in <module>
    from osgeo import gdal, ogr, osr
  File "/Produits/publics/x86_64.Linux.RH6/python/2.7.5b/lib/python2.7/site-packages/GDAL-1.11.0-py2.7-linux-x86_64.egg/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Produits/publics/x86_64.Linux.RH6/python/2.7.5b/lib/python2.7/site-packages/GDAL-1.11.0-py2.7-linux-x86_64.egg/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: libpq.so.5: cannot open shared object file: No such file or directory
-------------------------------

Il doit y avoir un problème de variables d'environnement, qui ne sont pas les mêmes entre les 2 exécutions.

J'ai préparé un fichier pbs qui appelle un script pyhton avec le strict minimum pour montrer le problème :

/home/user5/qtis/inglada/minimal.pbs
/home/user5/qtis/inglada/importgdal.py

Merci pour votre aide.
#+END_QUOTE
